name: anime
description: Lista de animes e suas classificações.

version: 1.3.0+30

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_database: ^7.1.2
  firebase_storage: ^10.0.1
  #google_mobile_ads: ^0.13.2
  google_sign_in: ^5.0.4
  network_to_file_image: ^3.0.0
  package_info: ^2.0.2
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.9
  youtube_player_flutter: ^8.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: ^0.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  adaptive_icon_background: '#ff9800'
  adaptive_icon_foreground: "assets/icons/ic_launcher_adaptive.png"
  image_path_android: "assets/icons/ic_launcher.png"
  image_path_ios: "assets/icons/ic_launcher_ios.png"
  android: true
  ios: true

flutter_launcher_name:
  name: 'Anime'

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family:  MyIcons
      fonts:
      - asset: assets/fonts/MyIcons.ttf
