name: anime
description: Lista de animes e suas classificações

version: 1.0.10+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
#  android_intent: ^0.3.7+3
#  device_apps: ^1.2.0
#  dio: any
  firebase_auth: ^0.16.1
  firebase_database: ^3.1.6
  google_sign_in: ^4.1.1
  package_info: ^0.4.0+16
  path_provider: ^1.6.11
  shared_preferences: ^0.5.8
  url_launcher: ^5.5.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: ^0.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  adaptive_icon_background: '#ff9800'
  adaptive_icon_foreground: "assets/icons/ic_launcher_adaptive.png"
  image_path_android: "assets/icons/ic_launcher.png"
  image_path_ios: "assets/icons/ic_launcher_ios.png"
  android: true
  ios: true

flutter_launcher_name:
  name: 'Anime'

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family:  MyIcons
      fonts:
      - asset: assets/fonts/MyIcons.ttf
