name: anime
description: Lista de animes e suas classificações

version: 1.0.21+21

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
#  android_intent: ^0.3.7+3
#  device_apps: ^1.2.0
#  dio: any
  clipboard_manager: ^0.0.4
  dynamic_theme: ^1.0.1
  firebase_admob: ^0.10.2
  firebase_auth: ^0.18.3+1
  firebase_database: ^4.3.0
  firebase_storage: ^5.1.0
  google_sign_in: ^4.5.6
  package_info: ^0.4.3+2
  path_provider: ^1.6.24
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_launcher_name: ^0.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  adaptive_icon_background: '#ff9800'
  adaptive_icon_foreground: "assets/icons/ic_launcher_adaptive.png"
  image_path_android: "assets/icons/ic_launcher.png"
  image_path_ios: "assets/icons/ic_launcher_ios.png"
  android: true
  ios: true

flutter_launcher_name:
  name: 'Anime'

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family:  MyIcons
      fonts:
      - asset: assets/fonts/MyIcons.ttf
